openapi: 3.0.3
info:
  title: Dataverse Access Datasetfields API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: Datasetfields
paths:
  /datasetfields/facetables:
    get:
      operationId: DatasetFields_listAllFacetableDatasetFields
      responses:
        '200':
          description: OK
      tags:
      - Datasetfields
