openapi: 3.0.3
info:
  title: Dataverse Access Sendfeedback API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: Sendfeedback
paths:
  /sendfeedback:
    post:
      operationId: SendFeedbackAPI_submitFeedback
      responses:
        '200':
          description: OK
      tags:
      - Sendfeedback
