openapi: 3.0.3
info:
  title: Dataverse Access Inbox API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: Inbox
paths:
  /inbox:
    post:
      operationId: LDNInbox_acceptMessage
      requestBody:
        content:
          application/ld+json:
            schema:
              type: string
          application/json-ld:
            schema:
              type: string
      responses:
        '200':
          description: OK
      tags:
      - Inbox
