openapi: 3.0.3
info:
  title: Dataverse Access replaceFilesInDataset API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: replaceFilesInDataset
  description: Replace a file to a dataset
paths:
  /datasets/{id}/replaceFiles:
    post:
      tags:
      - replaceFilesInDataset
      summary: Replace a set of files to a dataset
      description: Replace a set of files to a dataset
      operationId: Datasets_replaceFilesInDataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
      responses:
        '200':
          description: Files replaced successfully to dataset
  /files/{id}/replace:
    post:
      tags:
      - replaceFilesInDataset
      summary: Replace a file on a dataset
      description: Replace a file to a dataset
      operationId: Files_replaceFileInDataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
      responses:
        '200':
          description: File replaced successfully on the dataset
