openapi: 3.0.3
info:
  title: Dataverse Access Roles API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: Roles
paths:
  /roles:
    post:
      operationId: Roles_createNewRole
      parameters:
      - name: dvo
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Roles
  /roles/userSelectable:
    get:
      operationId: Roles_getUserSelectableRoles
      responses:
        '200':
          description: OK
      tags:
      - Roles
  /roles/{id}:
    get:
      operationId: Roles_viewRole
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Roles
    delete:
      operationId: Roles_deleteRole
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Roles
