openapi: 3.0.3
info:
  title: Dataverse Access addGlobusFilesToDataset API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: addGlobusFilesToDataset
  description: Uploads a Globus file for a dataset
paths:
  /datasets/{id}/addGlobusFiles:
    post:
      tags:
      - addGlobusFilesToDataset
      summary: Uploads a Globus file for a dataset
      description: Uploads a Globus file for a dataset
      operationId: Datasets_addGlobusFilesToDataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
      responses:
        '200':
          description: Globus file uploaded successfully to dataset
