openapi: 3.0.3
info:
  title: Dataverse Access uploadDatasetLogo API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: uploadDatasetLogo
  description: Uploads a logo for a dataset
paths:
  /datasets/{id}/thumbnail:
    post:
      tags:
      - uploadDatasetLogo
      summary: Uploads a logo for a dataset
      description: Uploads a logo for a dataset
      operationId: Datasets_uploadDatasetLogo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              format: binary
              type: string
      responses:
        '200':
          description: Dataset logo uploaded successfully
