openapi: 3.0.3
info:
  title: Dataverse Access addFilesToDataset API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: addFilesToDataset
  description: Uploads a set of files to a dataset
paths:
  /datasets/{id}/addFiles:
    post:
      tags:
      - addFilesToDataset
      summary: Uploads a set of files to a dataset
      description: Uploads a set of files to a dataset
      operationId: Datasets_addFilesToDataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
      responses:
        '200':
          description: Files uploaded successfully to dataset
