openapi: 3.0.3
info:
  title: Dataverse Access Metadatablocks API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: Metadatablocks
paths:
  /metadatablocks:
    get:
      operationId: MetadataBlocks_listMetadataBlocks
      parameters:
      - name: onlyDisplayedOnCreate
        in: query
        schema:
          type: boolean
      - name: returnDatasetFieldTypes
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
      tags:
      - Metadatablocks
  /metadatablocks/{identifier}:
    get:
      operationId: MetadataBlocks_getMetadataBlock
      parameters:
      - name: identifier
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Metadatablocks
