openapi: 3.0.3
info:
  title: Dataverse Access ExternalTools API
  description: Open source research data repository software.
  version: '6.8'
servers:
- url: https://dataverse.unc.edu/api
  description: UNC Dataverse production instance
tags:
- name: ExternalTools
paths:
  /externalTools:
    get:
      operationId: ExternalToolsApi_getExternalTools
      responses:
        '200':
          description: OK
      tags:
      - ExternalTools
    post:
      operationId: ExternalToolsApi_addExternalTool
      responses:
        '200':
          description: OK
      tags:
      - ExternalTools
  /externalTools/{id}:
    get:
      operationId: ExternalToolsApi_getExternalTool
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        '200':
          description: OK
      tags:
      - ExternalTools
    delete:
      operationId: ExternalToolsApi_deleteExternalTool
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        '200':
          description: OK
      tags:
      - ExternalTools
